<?php

/**
 * Base class that represents a row from the 'channel' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jul  6 14:53:10 2012
 *
 * @package    lib.model.om
 */
abstract class BaseChannel extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ChannelPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the icecast_port field.
	 * @var        string
	 */
	protected $icecast_port;

	/**
	 * The value for the port field.
	 * @var        string
	 */
	protected $port;

	/**
	 * The value for the slug field.
	 * @var        string
	 */
	protected $slug;

	/**
	 * @var        array Community[] Collection to store aggregation of Community objects.
	 */
	protected $collCommunitys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCommunitys.
	 */
	private $lastCommunityCriteria = null;

	/**
	 * @var        array ChannelTrack[] Collection to store aggregation of ChannelTrack objects.
	 */
	protected $collChannelTracks;

	/**
	 * @var        Criteria The criteria used to select the current contents of collChannelTracks.
	 */
	private $lastChannelTrackCriteria = null;

	/**
	 * @var        array TrackVote[] Collection to store aggregation of TrackVote objects.
	 */
	protected $collTrackVotes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTrackVotes.
	 */
	private $lastTrackVoteCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ChannelPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [icecast_port] column value.
	 * 
	 * @return     string
	 */
	public function getIcecastPort()
	{
		return $this->icecast_port;
	}

	/**
	 * Get the [port] column value.
	 * 
	 * @return     string
	 */
	public function getPort()
	{
		return $this->port;
	}

	/**
	 * Get the [slug] column value.
	 * 
	 * @return     string
	 */
	public function getSlug()
	{
		return $this->slug;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Channel The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ChannelPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Channel The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = ChannelPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [icecast_port] column.
	 * 
	 * @param      string $v new value
	 * @return     Channel The current object (for fluent API support)
	 */
	public function setIcecastPort($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->icecast_port !== $v) {
			$this->icecast_port = $v;
			$this->modifiedColumns[] = ChannelPeer::ICECAST_PORT;
		}

		return $this;
	} // setIcecastPort()

	/**
	 * Set the value of [port] column.
	 * 
	 * @param      string $v new value
	 * @return     Channel The current object (for fluent API support)
	 */
	public function setPort($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->port !== $v) {
			$this->port = $v;
			$this->modifiedColumns[] = ChannelPeer::PORT;
		}

		return $this;
	} // setPort()

	/**
	 * Set the value of [slug] column.
	 * 
	 * @param      string $v new value
	 * @return     Channel The current object (for fluent API support)
	 */
	public function setSlug($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slug !== $v) {
			$this->slug = $v;
			$this->modifiedColumns[] = ChannelPeer::SLUG;
		}

		return $this;
	} // setSlug()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->icecast_port = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->port = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->slug = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = ChannelPeer::NUM_COLUMNS - ChannelPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Channel object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ChannelPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ChannelPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collCommunitys = null;
			$this->lastCommunityCriteria = null;

			$this->collChannelTracks = null;
			$this->lastChannelTrackCriteria = null;

			$this->collTrackVotes = null;
			$this->lastTrackVoteCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ChannelPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseChannel:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ChannelPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseChannel:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ChannelPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseChannel:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseChannel:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ChannelPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ChannelPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ChannelPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ChannelPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCommunitys !== null) {
				foreach ($this->collCommunitys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collChannelTracks !== null) {
				foreach ($this->collChannelTracks as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTrackVotes !== null) {
				foreach ($this->collTrackVotes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ChannelPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCommunitys !== null) {
					foreach ($this->collCommunitys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collChannelTracks !== null) {
					foreach ($this->collChannelTracks as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTrackVotes !== null) {
					foreach ($this->collTrackVotes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ChannelPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getIcecastPort();
				break;
			case 3:
				return $this->getPort();
				break;
			case 4:
				return $this->getSlug();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ChannelPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getIcecastPort(),
			$keys[3] => $this->getPort(),
			$keys[4] => $this->getSlug(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ChannelPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setIcecastPort($value);
				break;
			case 3:
				$this->setPort($value);
				break;
			case 4:
				$this->setSlug($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ChannelPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIcecastPort($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPort($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setSlug($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ChannelPeer::DATABASE_NAME);

		if ($this->isColumnModified(ChannelPeer::ID)) $criteria->add(ChannelPeer::ID, $this->id);
		if ($this->isColumnModified(ChannelPeer::NAME)) $criteria->add(ChannelPeer::NAME, $this->name);
		if ($this->isColumnModified(ChannelPeer::ICECAST_PORT)) $criteria->add(ChannelPeer::ICECAST_PORT, $this->icecast_port);
		if ($this->isColumnModified(ChannelPeer::PORT)) $criteria->add(ChannelPeer::PORT, $this->port);
		if ($this->isColumnModified(ChannelPeer::SLUG)) $criteria->add(ChannelPeer::SLUG, $this->slug);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ChannelPeer::DATABASE_NAME);

		$criteria->add(ChannelPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Channel (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setIcecastPort($this->icecast_port);

		$copyObj->setPort($this->port);

		$copyObj->setSlug($this->slug);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCommunitys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCommunity($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getChannelTracks() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addChannelTrack($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTrackVotes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTrackVote($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Channel Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ChannelPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ChannelPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collCommunitys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCommunitys()
	 */
	public function clearCommunitys()
	{
		$this->collCommunitys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCommunitys collection (array).
	 *
	 * By default this just sets the collCommunitys collection to an empty array (like clearcollCommunitys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCommunitys()
	{
		$this->collCommunitys = array();
	}

	/**
	 * Gets an array of Community objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Channel has previously been saved, it will retrieve
	 * related Communitys from storage. If this Channel is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Community[]
	 * @throws     PropelException
	 */
	public function getCommunitys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommunitys === null) {
			if ($this->isNew()) {
			   $this->collCommunitys = array();
			} else {

				$criteria->add(CommunityPeer::CHANNEL_ID, $this->id);

				CommunityPeer::addSelectColumns($criteria);
				$this->collCommunitys = CommunityPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CommunityPeer::CHANNEL_ID, $this->id);

				CommunityPeer::addSelectColumns($criteria);
				if (!isset($this->lastCommunityCriteria) || !$this->lastCommunityCriteria->equals($criteria)) {
					$this->collCommunitys = CommunityPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCommunityCriteria = $criteria;
		return $this->collCommunitys;
	}

	/**
	 * Returns the number of related Community objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Community objects.
	 * @throws     PropelException
	 */
	public function countCommunitys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCommunitys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CommunityPeer::CHANNEL_ID, $this->id);

				$count = CommunityPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CommunityPeer::CHANNEL_ID, $this->id);

				if (!isset($this->lastCommunityCriteria) || !$this->lastCommunityCriteria->equals($criteria)) {
					$count = CommunityPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCommunitys);
				}
			} else {
				$count = count($this->collCommunitys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Community object to this object
	 * through the Community foreign key attribute.
	 *
	 * @param      Community $l Community
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCommunity(Community $l)
	{
		if ($this->collCommunitys === null) {
			$this->initCommunitys();
		}
		if (!in_array($l, $this->collCommunitys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCommunitys, $l);
			$l->setChannel($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Channel is new, it will return
	 * an empty collection; or if this Channel has previously
	 * been saved, it will retrieve related Communitys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Channel.
	 */
	public function getCommunitysJoinTrack($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCommunitys === null) {
			if ($this->isNew()) {
				$this->collCommunitys = array();
			} else {

				$criteria->add(CommunityPeer::CHANNEL_ID, $this->id);

				$this->collCommunitys = CommunityPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CommunityPeer::CHANNEL_ID, $this->id);

			if (!isset($this->lastCommunityCriteria) || !$this->lastCommunityCriteria->equals($criteria)) {
				$this->collCommunitys = CommunityPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		}
		$this->lastCommunityCriteria = $criteria;

		return $this->collCommunitys;
	}

	/**
	 * Clears out the collChannelTracks collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addChannelTracks()
	 */
	public function clearChannelTracks()
	{
		$this->collChannelTracks = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collChannelTracks collection (array).
	 *
	 * By default this just sets the collChannelTracks collection to an empty array (like clearcollChannelTracks());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initChannelTracks()
	{
		$this->collChannelTracks = array();
	}

	/**
	 * Gets an array of ChannelTrack objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Channel has previously been saved, it will retrieve
	 * related ChannelTracks from storage. If this Channel is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ChannelTrack[]
	 * @throws     PropelException
	 */
	public function getChannelTracks($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collChannelTracks === null) {
			if ($this->isNew()) {
			   $this->collChannelTracks = array();
			} else {

				$criteria->add(ChannelTrackPeer::CHANNEL_ID, $this->id);

				ChannelTrackPeer::addSelectColumns($criteria);
				$this->collChannelTracks = ChannelTrackPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ChannelTrackPeer::CHANNEL_ID, $this->id);

				ChannelTrackPeer::addSelectColumns($criteria);
				if (!isset($this->lastChannelTrackCriteria) || !$this->lastChannelTrackCriteria->equals($criteria)) {
					$this->collChannelTracks = ChannelTrackPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastChannelTrackCriteria = $criteria;
		return $this->collChannelTracks;
	}

	/**
	 * Returns the number of related ChannelTrack objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ChannelTrack objects.
	 * @throws     PropelException
	 */
	public function countChannelTracks(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collChannelTracks === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ChannelTrackPeer::CHANNEL_ID, $this->id);

				$count = ChannelTrackPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ChannelTrackPeer::CHANNEL_ID, $this->id);

				if (!isset($this->lastChannelTrackCriteria) || !$this->lastChannelTrackCriteria->equals($criteria)) {
					$count = ChannelTrackPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collChannelTracks);
				}
			} else {
				$count = count($this->collChannelTracks);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ChannelTrack object to this object
	 * through the ChannelTrack foreign key attribute.
	 *
	 * @param      ChannelTrack $l ChannelTrack
	 * @return     void
	 * @throws     PropelException
	 */
	public function addChannelTrack(ChannelTrack $l)
	{
		if ($this->collChannelTracks === null) {
			$this->initChannelTracks();
		}
		if (!in_array($l, $this->collChannelTracks, true)) { // only add it if the **same** object is not already associated
			array_push($this->collChannelTracks, $l);
			$l->setChannel($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Channel is new, it will return
	 * an empty collection; or if this Channel has previously
	 * been saved, it will retrieve related ChannelTracks from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Channel.
	 */
	public function getChannelTracksJoinTrack($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collChannelTracks === null) {
			if ($this->isNew()) {
				$this->collChannelTracks = array();
			} else {

				$criteria->add(ChannelTrackPeer::CHANNEL_ID, $this->id);

				$this->collChannelTracks = ChannelTrackPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ChannelTrackPeer::CHANNEL_ID, $this->id);

			if (!isset($this->lastChannelTrackCriteria) || !$this->lastChannelTrackCriteria->equals($criteria)) {
				$this->collChannelTracks = ChannelTrackPeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		}
		$this->lastChannelTrackCriteria = $criteria;

		return $this->collChannelTracks;
	}

	/**
	 * Clears out the collTrackVotes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTrackVotes()
	 */
	public function clearTrackVotes()
	{
		$this->collTrackVotes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTrackVotes collection (array).
	 *
	 * By default this just sets the collTrackVotes collection to an empty array (like clearcollTrackVotes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTrackVotes()
	{
		$this->collTrackVotes = array();
	}

	/**
	 * Gets an array of TrackVote objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Channel has previously been saved, it will retrieve
	 * related TrackVotes from storage. If this Channel is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TrackVote[]
	 * @throws     PropelException
	 */
	public function getTrackVotes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTrackVotes === null) {
			if ($this->isNew()) {
			   $this->collTrackVotes = array();
			} else {

				$criteria->add(TrackVotePeer::CHANNEL_ID, $this->id);

				TrackVotePeer::addSelectColumns($criteria);
				$this->collTrackVotes = TrackVotePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TrackVotePeer::CHANNEL_ID, $this->id);

				TrackVotePeer::addSelectColumns($criteria);
				if (!isset($this->lastTrackVoteCriteria) || !$this->lastTrackVoteCriteria->equals($criteria)) {
					$this->collTrackVotes = TrackVotePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTrackVoteCriteria = $criteria;
		return $this->collTrackVotes;
	}

	/**
	 * Returns the number of related TrackVote objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TrackVote objects.
	 * @throws     PropelException
	 */
	public function countTrackVotes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTrackVotes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TrackVotePeer::CHANNEL_ID, $this->id);

				$count = TrackVotePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TrackVotePeer::CHANNEL_ID, $this->id);

				if (!isset($this->lastTrackVoteCriteria) || !$this->lastTrackVoteCriteria->equals($criteria)) {
					$count = TrackVotePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTrackVotes);
				}
			} else {
				$count = count($this->collTrackVotes);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TrackVote object to this object
	 * through the TrackVote foreign key attribute.
	 *
	 * @param      TrackVote $l TrackVote
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTrackVote(TrackVote $l)
	{
		if ($this->collTrackVotes === null) {
			$this->initTrackVotes();
		}
		if (!in_array($l, $this->collTrackVotes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTrackVotes, $l);
			$l->setChannel($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Channel is new, it will return
	 * an empty collection; or if this Channel has previously
	 * been saved, it will retrieve related TrackVotes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Channel.
	 */
	public function getTrackVotesJoinTrack($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ChannelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTrackVotes === null) {
			if ($this->isNew()) {
				$this->collTrackVotes = array();
			} else {

				$criteria->add(TrackVotePeer::CHANNEL_ID, $this->id);

				$this->collTrackVotes = TrackVotePeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TrackVotePeer::CHANNEL_ID, $this->id);

			if (!isset($this->lastTrackVoteCriteria) || !$this->lastTrackVoteCriteria->equals($criteria)) {
				$this->collTrackVotes = TrackVotePeer::doSelectJoinTrack($criteria, $con, $join_behavior);
			}
		}
		$this->lastTrackVoteCriteria = $criteria;

		return $this->collTrackVotes;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCommunitys) {
				foreach ((array) $this->collCommunitys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collChannelTracks) {
				foreach ((array) $this->collChannelTracks as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTrackVotes) {
				foreach ((array) $this->collTrackVotes as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCommunitys = null;
		$this->collChannelTracks = null;
		$this->collTrackVotes = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseChannel:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseChannel::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseChannel
