<?php


/**
 * Skeleton subclass for performing query and update operations on the 'channel' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jul  4 23:31:05 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ChannelPeer extends BaseChannelPeer {

	public static function retrieveBySlug($slug){
		$c = new Criteria;
		$c->add(ChannelPeer::SLUG, $slug);

		return self::doSelectOne($c);
	}

	public static function retrieveByName($name)
	{
		$c = new Criteria;
		$c->add(ChannelPeer::NAME, $name);
		return self::doSelectOne($c);
	}

} // ChannelPeer
