<?php


/**
 * Skeleton subclass for representing a row from the 'channel' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jul  4 23:31:05 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Channel extends BaseChannel {
	
	public function getServer(){
		return 'http://www.icecast-streaming.com.local:'.$this->getIcecastPort().'/'.$this->getSlug();
	}

	public function getNumberOfListeners(){
		$icecast = new IcecastUtility($this->getServer());
		$icecast->fetch();
		$info = $icecast->getStatus();

		return isset($info['listeners']) ? $info['listeners'] : null;
	}

} // Channel
