<?php


/**
 * Skeleton subclass for performing query and update operations on the 'track' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jun 22 14:57:07 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TrackPeer extends BaseTrackPeer {

	public static function getAvailableTracksCriteria(Channel $channel=null){
		$criteria = new Criteria();
		$criteria->addJoin(TrackPeer::ID, ChannelTrackPeer::TRACK_ID, Criteria::JOIN);
		$criteria->add(ChannelTrackPeer::CHANNEL_ID, $channel->getId());
		
		$communityJoin = array(
			array(TrackPeer::ID, CommunityPeer::TRACK_ID),
			array(CommunityPeer::CHANNEL_ID, $channel->getId()),
		);

		$criteria->addMultipleJoin($communityJoin, Criteria::LEFT_JOIN);
		$criteria->add(CommunityPeer::TRACK_ID, NULL, Criteria::ISNULL);
		$criteria->addDescendingOrderByColumn('RAND()');
		
		return $criteria;
	}

	public static function getTracksInPlaylistCriteria(Channel $channel=null){
		$criteria = new Criteria();
		$criteria->addJoin(TrackPeer::ID, TrackVotePeer::TRACK_ID, Criteria::JOIN);

		$communityJoin = array(
			array(TrackVotePeer::TRACK_ID, CommunityPeer::TRACK_ID),
			array(CommunityPeer::CHANNEL_ID, $channel->getId()),
		);

		$criteria->addMultipleJoin($communityJoin, Criteria::LEFT_JOIN);
		$criteria->add(CommunityPeer::TRACK_ID, NULL, Criteria::ISNOTNULL);
		$criteria->addDescendingOrderByColumn(TrackVotePeer::TEMP_VOTES);

		return $criteria;
	}

	public static function getTopNTracksInQueueCriteria(Channel $channel=null, $n=3){
		$criteria = new Criteria();
		$criteria->addJoin(TrackPeer::ID, TrackVotePeer::TRACK_ID);
		$criteria->add(TrackVotePeer::CHANNEL_ID, $channel->getId());

		$criteria->setLimit($n);
		$criteria->addDescendingOrderByColumn(TrackVotePeer::TEMP_VOTES);
		
		return $criteria;
	}

} // TrackPeer
