<?php


/**
 * Skeleton subclass for performing query and update operations on the 'track_vote' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jun 22 14:57:07 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TrackVotePeer extends BaseTrackVotePeer {

	public static function doVote(Track $track=null, Channel $channel){
		$id = $track->getId();             
		$vote = TrackVotePeer::retrieveByPk($track->getId(), $channel->getId());

		if(!$vote){
			$c = new Criteria();
			$c->add(TrackVotePeer::TRACK_ID, $track->getId());
			$c->add(TrackVotePeer::CHANNEL_ID, $channel->getId());
			$id = TrackVotePeer::doInsert($c);
		}
		
		$vote = TrackVotePeer::retrieveByPk($track->getId(), $channel->getId());
		$vote->setAllVotes($vote->getAllVotes()+1);
		$vote->setTempVotes($vote->getTempVotes()+1);
		$vote->save();

		return $vote;
	}

	public static function resetChannelVotes(Channel $channel){
		$c = new Criteria();
		$c->add(TrackVotePeer::CHANNEL_ID, $channel->getId());

		$all = self::doSelect($c);
		
		foreach($all as $a){
			$a->setTempVotes(0);
			$a->save();
		}
	}

} // TrackVotePeer
